-- --------------------------------------------------------
-- Host:                         10.26.102.200
-- Server version:               5.7.24-0ubuntu0.16.04.1 - (Ubuntu)
-- Server OS:                    Linux
-- HeidiSQL Version:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for USUARIOS
CREATE DATABASE IF NOT EXISTS `USUARIOS` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `USUARIOS`;


-- Dumping structure for table USUARIOS.TBL_PERMISSOES
CREATE TABLE IF NOT EXISTS `TBL_PERMISSOES` (
  `ID_PERMISSAO` int(11) NOT NULL AUTO_INCREMENT,
  `NM_PERMISSAO` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID_PERMISSAO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table USUARIOS.TBL_PERMISSOES_USUARIOS
CREATE TABLE IF NOT EXISTS `TBL_PERMISSOES_USUARIOS` (
  `ID_PERMISSAO_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_PERMISSAO` int(11) NOT NULL,
  `ID_USUARIO` int(11) NOT NULL,
  PRIMARY KEY (`ID_PERMISSAO_USUARIO`),
  KEY `FK_USUARIO_PERMISSAO` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.


-- Dumping structure for table USUARIOS.TBL_USUARIOS
CREATE TABLE IF NOT EXISTS `TBL_USUARIOS` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `ID_TURMA` int(11) NOT NULL DEFAULT '1',
  `ID_SUPERVISAO` int(11) DEFAULT NULL,
  `NM_USUARIO` varchar(50) NOT NULL,
  `CD_MATRICULA` varchar(50) NOT NULL,
  `DS_SENHA` varchar(300) NOT NULL,
  `DS_EMAIL` varchar(50) NOT NULL,
  `TP_FOTO_USUARIO` longblob NOT NULL,
  `BT_ATIVO` bit(1) DEFAULT b'1',
  `NR_SAP` varchar(50) DEFAULT NULL,
  `ID_CENTRO_TRABALHO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  KEY `FKcod_supervisao` (`ID_SUPERVISAO`),
  CONSTRAINT `FK1_SUPERVISAO` FOREIGN KEY (`ID_SUPERVISAO`) REFERENCES `LOCACAO`.`TBL_SUPERVISOES` (`ID_SUPERVISAO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
